# Generated by Django 5.0.3 on 2024-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nicho',
            fields=[
                ('id_nicho', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_nicho', models.PositiveIntegerField()),
                ('local', models.CharField(max_length=100, null=True)),
                ('observacao', models.TextField(null=True)),
            ],
            options={
                'db_table': 'nicho',
            },
        ),
    ]
