# Generated by Django 5.0.3 on 2024-03-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_livro', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('quantidade_exemplar', models.IntegerField()),
                ('saldo_exemplar', models.IntegerField()),
                ('observacao_livro', models.TextField(null=True)),
                ('id_nicho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nicho')),
            ],
            options={
                'db_table': 'livro',
            },
        ),
    ]
